// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Creds struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type UserData struct {
	ID      string `json:"id"`
	Token   string `json:"token"`
	Balance string `json:"balance"`
	Bonus   string `json:"bonus"`
	Phone   string `json:"phone"`
	Name    string `json:"name"`
}
